preinit: make factory reset atomic, to be tested

diff --git a/meta/recipes-core/base-files/base-files-os/preinit b/meta/recipes-core/base-files/base-files-os/preinit
--- a/meta/recipes-core/base-files/base-files-os/preinit
+++ b/meta/recipes-core/base-files/base-files-os/preinit
@@ -138,7 +138,7 @@ preinit_manage_reset() {
         return 1
     fi
 
-    # Detect boot_state
+    # Detect boot_state from MCU
     BOOT_STATE=$(eval "$MACHINE_INFO -n -f BOOT_STATE" 2> /dev/null)
     if [ $? -ne 0 ]; then
         echo "Error trying to read boot state:"
@@ -152,15 +152,21 @@ preinit_manage_reset() {
         echo "Factory reset required, triggered by user"
         RESET_USER=1
     else
-        # Test now first init flag presence
-        os_first_init_has_started "/mnt/ubidata/overlay/user/diff/var/lib/os"
-        if [ $? -eq 1 ]; then
-            # Previous first init sequence has been done but not completed, need overlay cleaning
-            echo "Factory reset required, triggered by first init unconsistent state"
+        FACTORY_RESET_PENDING=$(printenv factory_reset_pending)
+        if [ "$FACTORY_RESET_PENDING" == "1" ]; then
+            # Previous factory reset started but not completed
+            echo "Factory reset required, previous did not complete"
         else
-            echo "Factory reset not required, pass"
-            return 0
-        fi
+            # Test now first init flag presence
+            os_first_init_has_started "/mnt/ubidata/overlay/user/diff/var/lib/os"
+            if [ $? -eq 1 ]; then
+                # Previous first init sequence has been done but not completed, need overlay cleaning
+                echo "Factory reset required, triggered by first init unconsistent state"
+            else
+                echo "Factory reset not required, pass"
+                return 0
+            fi
+        fi 
     fi
 
     # No need to revert the running partition since the factory reset
@@ -173,6 +179,11 @@ preinit_manage_reset() {
     if [ $UPGRADE_AVAILABLE -eq 1 ]; then
         echo "Upgrade is pending while doing a factory reset, something which should not happen."
     fi
+    # Keep track of the factory reset inside bootloader to ensure atomic operation
+    echo "Beginning of procedure..."
+    if [ "$FACTORY_RESET_PENDING" != "1" ]; then
+        setenv factory_reset_pending 1
+    fi
     echo "Removing existing overlay diff content"
     # Start cleaning system
     rm -rf /mnt/ubidata/overlay/user/diff/*
@@ -182,7 +193,7 @@ preinit_manage_reset() {
     sync
 
     if [ $RESET_USER -eq 1 ]; then
-        echo "Clearing factory reset state"
+        echo "Clearing factory reset state (mcu)"
 
         RET=$(eval "$MACHINE_INFO --reset" 2> /dev/null)
         if [ $? -ne 0 ]; then
@@ -191,6 +202,9 @@ preinit_manage_reset() {
             echo "continue"
         fi
     fi
+
+    echo "Factory reset completed"
+    setenv factory_reset_pending
     echo "======== done ========="
 
     # No error
